### PR TITLE
SPT-12291 Revert Angular 13 Updates

### PR DESCRIPTION
**Pull request by ischultz**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
The project was previously updated to Angular 13 and converted to use ESLint

**What is the new behavior?**
Reverted Angular 13 and ESLint changes so that a release could be made with the existing version of Angular but with the vulnerability updates.
Also switched away from node-sass to sass to resolve a vulnerability and due to node-sass being deprecated.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by CalebBass — APPROVED** [review]
Revisions look good.

**Comment by ischultz** [comment]
After further discussion, we will not revert these changes.

**Comment by bahizi** [comment]
@ischultz do you know when the angular 13 upgrade changes will be released to npm?

**Comment by ischultz** [comment]
@bahizi I unfortunately cannot provide you with an estimated time frame but please know that we are working on it!

**Comment by Hypercubed** [comment]
@bahizi What issue are you having with the current release.  It does work in Angular 13.

**Comment by bahizi** [comment]
@Hypercubed oh yeah it works with  no issues once built and deployed. it's just that I have some automated dependency management tools monitoring my repo and they don't seem to like that per `@swimlane/dnd`'s package.json angular 13 is not supported. Also `npm@7+` is also rather more strict about missing peer dependencies without the `--legacy-peer-deps` flag it makes ci builds fail if a certain package's dependency is missing.

**Pull request closed without merging**
