### PR TITLE
Resolve Angular Ivy deep link warning

### PR DESCRIPTION
**Pull request by SamuelMS**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Warning during compilation with Angular Ivy:

```
Warning: Entry point '@swimlane/ngx-dnd' contains deep imports into '/Users/samuelms/Documents/GitHub/datamonkey-frontend/node_modules/@angular/compiler/src/core'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
```

See #160.

**What is the new behavior?**

No warning during compilation.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

@Hypercubed Very minor change to imports to resolve a warning during Angular Ivy compilation.

### CODE REVIEW

**Comment by Hypercubed** [comment]
@SamuelMS Wasn't this fixed in the latest patch of Angular?

**Comment by SamuelMS** [comment]
@Hypercubed I don't think so – unless you mean Angular 10, which is still in RC. We're running `9.1.9` and still seeing this.

**Comment by Hypercubed** [comment]
@SamuelMS  Please try v8.1.2

**Comment by SamuelMS** [comment]
LGTM, thanks.

**Pull request closed without merging**
